config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :assigned_employees
  resources :service_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assigned_employee.rb
class AssignedEmployee < ApplicationRecord
	
	has_many :taskempoloyees, dependent: :destroy
	has_many :tasks, :through => :taskempoloyees
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
	
	has_many :taskservices, dependent: :destroy
	has_many :tasks, :through => :taskservices
end

app/models/task.rb
class Task < ApplicationRecord
	
	has_many :taskempoloyees, dependent: :destroy
	has_many :assigned_employees, :through => :taskempoloyees

	has_many :taskservices, dependent: :destroy
	has_many :service_types, :through => :taskservices
end

app/models/taskempoloyee.rb
class Taskempoloyee < ApplicationRecord
	belongs_to :task
	belongs_to :assigned_employee


end

app/models/taskservice.rb
class Taskservice < ApplicationRecord

	belongs_to :task
	belongs_to :service_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assigned_employees_controller.rb
class AssignedEmployeesController < ApplicationController
  before_action :set_assigned_employee, only: [:show, :edit, :update, :destroy]

  # GET /assigned_employees
  # GET /assigned_employees.json
  def index
    @assigned_employees = AssignedEmployee.all
  end

  # GET /assigned_employees/1
  # GET /assigned_employees/1.json
  def show
  end

  # GET /assigned_employees/new
  def new
    @assigned_employee = AssignedEmployee.new
  end

  # GET /assigned_employees/1/edit
  def edit
  end

  # POST /assigned_employees
  # POST /assigned_employees.json
  def create
    @assigned_employee = AssignedEmployee.new(assigned_employee_params)

    respond_to do |format|
      if @assigned_employee.save
        format.html { redirect_to @assigned_employee, notice: 'Assigned employee was successfully created.' }
        format.json { render :show, status: :created, location: @assigned_employee }
      else
        format.html { render :new }
        format.json { render json: @assigned_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assigned_employees/1
  # PATCH/PUT /assigned_employees/1.json
  def update
    respond_to do |format|
      if @assigned_employee.update(assigned_employee_params)
        format.html { redirect_to @assigned_employee, notice: 'Assigned employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @assigned_employee }
      else
        format.html { render :edit }
        format.json { render json: @assigned_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assigned_employees/1
  # DELETE /assigned_employees/1.json
  def destroy
    @assigned_employee.destroy
    respond_to do |format|
      format.html { redirect_to assigned_employees_url, notice: 'Assigned employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assigned_employee
      @assigned_employee = AssignedEmployee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assigned_employee_params
      params.require(:assigned_employee).permit(:name)
    end
end

app/controllers/service_types_controller.rb
class ServiceTypesController < ApplicationController
  before_action :set_service_type, only: [:show, :edit, :update, :destroy]

  # GET /service_types
  # GET /service_types.json
  def index
    @service_types = ServiceType.all
  end

  # GET /service_types/1
  # GET /service_types/1.json
  def show
  end

  # GET /service_types/new
  def new
    @service_type = ServiceType.new
  end

  # GET /service_types/1/edit
  def edit
  end

  # POST /service_types
  # POST /service_types.json
  def create
    @service_type = ServiceType.new(service_type_params)

    respond_to do |format|
      if @service_type.save
        format.html { redirect_to @service_type, notice: 'Service type was successfully created.' }
        format.json { render :show, status: :created, location: @service_type }
      else
        format.html { render :new }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_types/1
  # PATCH/PUT /service_types/1.json
  def update
    respond_to do |format|
      if @service_type.update(service_type_params)
        format.html { redirect_to @service_type, notice: 'Service type was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_type }
      else
        format.html { render :edit }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_types/1
  # DELETE /service_types/1.json
  def destroy
    @service_type.destroy
    respond_to do |format|
      format.html { redirect_to service_types_url, notice: 'Service type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_type
      @service_type = ServiceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_type_params
      params.require(:service_type).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @taskemployee = @task.taskempoloyees.build
    @taskservice = @task.taskservices.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :contact, :area_line, :address_line, :status, :priority, :billing, :payment_status, :remark, :service_info, :service_type_ids => [], :assigned_employee_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assigned_employees_helper.rb
module AssignedEmployeesHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/assigned_employees/_form.html.erb
<%= form_with(model: assigned_employee, local: true) do |form| %>
  <% if assigned_employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assigned_employee.errors.count, "error") %> prohibited this assigned_employee from being saved:</h2>

      <ul>
      <% assigned_employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assigned_employees/edit.html.erb
<h1>Editing Assigned Employee</h1>

<%= render 'form', assigned_employee: @assigned_employee %>

<%= link_to 'Show', @assigned_employee %> |
<%= link_to 'Back', assigned_employees_path %>

app/views/assigned_employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assigned Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assigned_employees.each do |assigned_employee| %>
      <tr>
        <td><%= assigned_employee.name %></td>
        <td><%= link_to 'Show', assigned_employee %></td>
        <td><%= link_to 'Edit', edit_assigned_employee_path(assigned_employee) %></td>
        <td><%= link_to 'Destroy', assigned_employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assigned Employee', new_assigned_employee_path %>

app/views/assigned_employees/new.html.erb
<h1>New Assigned Employee</h1>

<%= render 'form', assigned_employee: @assigned_employee %>

<%= link_to 'Back', assigned_employees_path %>

app/views/assigned_employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assigned_employee.name %>
</p>

<%= link_to 'Edit', edit_assigned_employee_path(@assigned_employee) %> |
<%= link_to 'Back', assigned_employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServiceTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/service_types/_form.html.erb
<%= form_with(model: service_type, local: true) do |form| %>
  <% if service_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_type.errors.count, "error") %> prohibited this service_type from being saved:</h2>

      <ul>
      <% service_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/service_types/edit.html.erb
<h1>Editing Service Type</h1>

<%= render 'form', service_type: @service_type %>

<%= link_to 'Show', @service_type %> |
<%= link_to 'Back', service_types_path %>

app/views/service_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_types.each do |service_type| %>
      <tr>
        <td><%= service_type.name %></td>
        <td><%= link_to 'Show', service_type %></td>
        <td><%= link_to 'Edit', edit_service_type_path(service_type) %></td>
        <td><%= link_to 'Destroy', service_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Type', new_service_type_path %>

app/views/service_types/new.html.erb
<h1>New Service Type</h1>

<%= render 'form', service_type: @service_type %>

<%= link_to 'Back', service_types_path %>

app/views/service_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service_type.name %>
</p>

<%= link_to 'Edit', edit_service_type_path(@service_type) %> |
<%= link_to 'Back', service_types_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% @areas = "Adarsh Nagar", "Agra Road", "Ajmer Road", "Ajmeri Gate", "Ambabari", "Amer Road", "Bais Godam", "Bajaj Nagar", "Bani Park", "Bapu Bazaar", "Bapu Nagar", "Barkat Nagar", "Bhawani Singh Road", "Biseswarji", "Brahmapuri", "Chandpol", "Civil Lines", "Durgapura", "Gangori Bazar", "Ghat Darwaza", "Gopalpura", "Indira Bazar", "Jagatpura", "Jalupura", "Janata Colony", "Jawaharlal Nehru Marg", "Jawahar Nagar", "Jhotwara", "Jhotwara Industrial Area", "Jhotwara Road", "Johari Bazar", "Jyothi Nagar", "Kalwar Road", "Kartarpur", "Khatipura", "Mahesh Nagar", "Malviya Nagar", "Mansarovar", "Mirza Ismail Road", "Motidungri Marg", "Muralipura", "New Colony", "Pink City", "Raja Park", "Ramganj", "Sanganer", "Sansar Chandra Road", "Sethi Colony", "Shastri Nagar", "Shyam Nagar", "Sikar Road", "Sindhi Camp", "Sirsi Road", "Sitapura Industrial Area", "Sodala", "Subhash Nagar", "Sudharshanpura Industrial Area", "Surajpol Bazar", "Tilak Nagar", "Tonk Phatak", "Tonk Road", "Transport Nagar", "Vaishali Nagar", "Vidhyadhar Nagar", "Vishwakarma Industrial Area"
%>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.number_field :contact %>
  </div>

  <div class="field">
    <%= form.label :area_line %>
    <%= form.select(:area_line, @areas, {}) %>
  </div>

  <div class="field">
    <%= form.label :address_line %>
    <%= form.text_field :address_line %>
  </div>

  <div class="field">
    <%= form.label :service_type_id %>
    <%= form.fields_for(@taskservice)  do |ab| %>
        <%= form.collection_select(:service_type_ids, ServiceType.all, :id, :name, {}, {:multiple => true, id: "service_type"})%>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :service_info %>
    <%= form.text_field :service_info %>
  </div>

  <div class="field">
    <%= form.label :assigned_employee_id %>
    <%= form.fields_for(@taskemployee)  do |ab| %>
        <%= form.collection_select(:assigned_employee_ids, AssignedEmployee.all, :id, :name, {}, {:multiple => true, id: "employee"})%>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select(:status, options_for_select([['COMPLETED','COMPLETED'], ['IN PROGRESS', 'IN PROGRESS'], ['PENDING','PENDING']]), { include_blank: ""}) %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select(:priority, options_for_select([['HIGH','HIGH'], ['LOW', 'LOW'], ['MEDIUM','MEDIUM'], ['URGENT','URGENT']]), { include_blank: ""}) %>
  </div>

  <div class="field">
    <%= form.label :billing %>
    <%= form.select(:billing, options_for_select([['BILLED','BILLED'], ['NA', 'NA'], ['NOT TO BE BILLED','NOT TO BE BILLED']]), { include_blank: ""}) %>
  </div>

  <div class="field">
    <%= form.label :payment_status %>
    <%= form.select(:payment_status, options_for_select([['DUE','DUE'], ['NA', 'NA'], ['OTHER','OTHER'], ['RECEIVED','RECEIVED']]), { include_blank: ""}) %>
  </div>

  <div class="field">
    <%= form.label :remark %>
    <%= form.text_field :remark %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
  $('#service_type').multiselect({

  });
   $('#employee').multiselect({

  });
</script>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th>Area line</th>
      <th>Address line</th>
      <th>Service type</th>
      <th>Service info</th>
      <th>Assigned employee</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Billing</th>
      <th>Payment status</th>
      <th>Remark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.contact %></td>
        <td><%= task.area_line %></td>
        <td><%= task.address_line %></td>
        <td><%= task.service_type_id %></td>
        <td><%= task.service_info %></td>
        <td><%= task.assigned_employee_id %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.billing %></td>
        <td><%= task.payment_status %></td>
        <td><%= task.remark %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @task.contact %>
</p>

<p>
  <strong>Area line:</strong>
  <%= @task.area_line %>
</p>

<p>
  <strong>Address line:</strong>
  <%= @task.address_line %>
</p>

<p>
  <strong>Service type:</strong>
  <% @task.service_types.each do |st| %>
    <%= st.name %>,
  <% end %>
</p>

<p>
  <strong>Service info:</strong>
  <%= @task.service_info %>
</p>

<p>
  <strong>Assigned employee:</strong>
  <% @task.assigned_employees.each do |ae| %>
    <%= ae.name %>,
  <% end %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Billing:</strong>
  <%= @task.billing %>
</p>

<p>
  <strong>Payment status:</strong>
  <%= @task.payment_status %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @task.remark %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>